[package]
name = "wasmer-as"
version = "0.1.0"
authors = ["Andrey Kuznetsov <fear@loathing.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime = "^0.13.1"
ucs2 = "^0.3.1"
